pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '*/htmlcov/*'
        }
    }
} 